### ISSUE TITLE
Wow this is not out of the box

### ISSUE THREAD

**Issue by JoshuaShelswell** [guysoft/MagicMirrorOS#24]
npm doesnt seem to work with this, not sure whats up with node and relation to docker

**Comment by JoshuaShelswell** [comment]
just using docker commands seems to work idk

**Comment by guysoft** [comment]
Can you be more specific as to what you are trying to do?

MagicMirrorOS uses a docker container in order to provide automatic updates. From what I understand have you already got MagicMirror to start?

**Comment by JoshuaShelswell** [comment]
i loaded your image onto the SD card and all it did was give me a black screen, i managed to figure out that you can type magicmirroros:8080 on my other computer and saw that it was running, i then figured out i could SSH into it with putty just putting in magicmirroros and was left on port 22, still worked, i then globally removed npm and node because it kept telling me npm wont work with that version, after i removed them and rebooted, i got the screen on my hdmi montior finally which was a + i still had the node issue however the files were not in the right place apparently i had to move them with 

sudo cp -avr /home/pi/node_modules/9/server.js /home/pi


then 

sudo cp -avr /home/pi/node_modules/9/package.json /home/pi

after i did this i could now use npm and got everything running, and now im starting to add modules with mmpm so im winning, but yeah you need to let people know this info in the readme about ssh because i didnt even know if it was enabled, also the node issue, also the fact you can check on another computer if its hooked up to the network if you get a black screen, cause it took me all day to figure this stuff out and you guys should honestly have a separate discord set up for this because when you go to the magicmirror discord they just say we cant help you because your fork has nothing to do with them, so do these things please, otherwise nice job

**Comment by guysoft** [comment]
@khassel is the black screen a bug or something intentional for a mirror?
If it is its worth mentioning in the readme.

* The ssh is in the readme file.
* The webserver on port 8080 is not and is worth adding.

**Comment by khassel** [comment]
I'm not sure what @JoshuaShelswell did exactly.

There is no node or npm installed in MagicMirrorOS, this stuff is included in the docker image.
So may he installed the plain MM stuff again on top of MM-OS?

I think many people are not aware of the technical setup here (although described in the readme), which is
1. the MM-OS as a "minified raspbian"
2. the [docker setup of MM](https://gitlab.com/khassel/magicmirror)

We may should mention in the readme that the first start takes long, depending on the hardware, because the docker image is pulled the first time which can take up to 5 min on poor hardware (this could be the cause for the black screen).

The general thing is, that we should not "sell" this setup as e.g. "simple" or "running out of the box".
People who don't know anything about linux and/or docker can quickly setup MM with MM-OS, but this works only for the plain default setup. When they begin to change the setup of MM (e.g. installing modules) they need knowledge of linux/docker and they have to deal with this setup and the [docker setup](https://gitlab.com/khassel/magicmirror). Otherwise this will lead to frustration on their side (and on our side too).

> you guys should honestly have a separate discord set up for this because when you go to the magicmirror discord they just say we cant help you because your fork has nothing to do with them

I look into this channel nearly dayly. But at the time I saw your discord posts you had already "solved" your problem and also this issue was updated and closed. We cannot give live support, I have a real job beside this project ...

@guysoft  By the way, some people in discord and in the mm-forum are "shooting" regularly against this project with comments like "too complicated", "not needed", "use the standard setup with the scripts of sdetweil" ...

**Comment by JoshuaShelswell** [comment]
well i did a fresh install and enabled hdmi_safe=1, it booted up fine and started displaying no problem, maybe its my monitor i dont know. and @khassel didnt know you were in the discord already, you should probably just put that you can find me in that discord on the documentation instead of starting an entire new discord, i actually would prefer to run this over the standard setup to be honest, and you should probably add in the main documentation in the how to use it section about the image taking time to download, and you might be right about node showing up by accident because it's not there on the fresh install, so not sure how it ended up there before, i didnt install it myself because i only noticed it when i tried to install npm and noticed it was there, it couldve possibly been installed with npm and then i had to move the files to the appropriate folder which would be a thing to note if people are trying to use npm and node

**Comment by JoshuaShelswell** [comment]
maybe also add you can check the status through ssh in the documentation with

systemctl status docker

**Comment by JoshuaShelswell** [comment]
interesting i enabled 
hdmi_safe=1
disable_overscan=1
hdmi_force_hotplug=1
hdmi_mode=0  (i changed this to seee what would happen but it doesnt matter probably)

and then the monitor turned on after reboot and i see 1 red thing in the list of [OK] stuff but it goes too fast for me to know what it is, i recommented them and the screen is still working, dunno what it did but so far ive done that twice now so im not sure whats wrong with your setup
