### ISSUE TITLE
Blank screen after some hours - breakpoint debug exception

### ISSUE THREAD

**Issue by bergernetch** [guysoft/MagicMirrorOS#50]
After a few hours, the screen turns blank (black).

The error message in dmesg is 
`Unhandled prefetch abort: breakpoint debug exception (0x002) at 0x03658e54`

docker-compose logs shows nothing.

I can restore it by running 
`cd /home/pi/magicmirror/run && docker-compose restart`

Could this be an error in Electron itself?

**Comment by khassel** [comment]
Never saw such an error before, there are 2 things you could try:

- disable all modules one by one to check if this is caused by a specific module
- increase `shm_size` in your `docker-compose.yml` e.g. to `256mb` (see [the faq](https://khassel.gitlab.io/magicmirror/faq/#running-on-a-raspberry-pi-ends-with-a-white-or-black-screen-after-a-while))

**Comment by bergernetch** [comment]
I tried with a second Raspberry Pi, but it happened again.
So I installed a fresh Raspian and the did a classic MagicMirror install without Docker. 
Now everything runs fine.
